name: Build and Push to ECR and Deploy to ECS

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: lynk-api
  TASK_DEFINITION: lynk-api-prod
  SERVICE_NAME: lynk-api-prod
  CLUSTER_NAME: lynk-api-prod

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
 

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Register task definition
      id: register-task-definition
      run: |
        TASK_DEFINITION=$(sed -e "s|<IMAGE_NAME>|${{ steps.login-ecr.outputs.registry }}/lynk-api-prod:latest|g" task-definition.json)
        echo $TASK_DEFINITION > temp.json
        aws ecs register-task-definition --cli-input-json file://temp.json

    - name: Update ECS service
      run: |
        aws ecs update-service --cluster lynk-api --service lynk-api --task-definition ${{ steps.register-task-definition.outputs.task-definition-arn }}
   
    - name: Update ECS service desired task to 0
      run: |
        aws ecs update-service --cluster lynk-api --service lynk-api --desired-count 0

    - name: Update ECS service desired task to 1
      run: |
        aws ecs update-service --cluster lynk-api --service lynk-api --desired-count 1 --desired-count 1
